/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsFormRouteImport } from './routes/students/form'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as StudentsIdEditRouteImport } from './routes/students/$id/edit'
import { Route as StudentsIdDetailsRouteImport } from './routes/students/$id/details'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsFormRoute = StudentsFormRouteImport.update({
  id: '/students/form',
  path: '/students/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdEditRoute = StudentsIdEditRouteImport.update({
  id: '/students/$id/edit',
  path: '/students/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdDetailsRoute = StudentsIdDetailsRouteImport.update({
  id: '/students/$id/details',
  path: '/students/$id/details',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/students/form': typeof StudentsFormRoute
  '/students/$id/details': typeof StudentsIdDetailsRoute
  '/students/$id/edit': typeof StudentsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/students/form': typeof StudentsFormRoute
  '/students/$id/details': typeof StudentsIdDetailsRoute
  '/students/$id/edit': typeof StudentsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/students/form': typeof StudentsFormRoute
  '/students/$id/details': typeof StudentsIdDetailsRoute
  '/students/$id/edit': typeof StudentsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/students/form'
    | '/students/$id/details'
    | '/students/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/students/form'
    | '/students/$id/details'
    | '/students/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/students/form'
    | '/students/$id/details'
    | '/students/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  StudentsFormRoute: typeof StudentsFormRoute
  StudentsIdDetailsRoute: typeof StudentsIdDetailsRoute
  StudentsIdEditRoute: typeof StudentsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/form': {
      id: '/students/form'
      path: '/students/form'
      fullPath: '/students/form'
      preLoaderRoute: typeof StudentsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id/edit': {
      id: '/students/$id/edit'
      path: '/students/$id/edit'
      fullPath: '/students/$id/edit'
      preLoaderRoute: typeof StudentsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id/details': {
      id: '/students/$id/details'
      path: '/students/$id/details'
      fullPath: '/students/$id/details'
      preLoaderRoute: typeof StudentsIdDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  StudentsFormRoute: StudentsFormRoute,
  StudentsIdDetailsRoute: StudentsIdDetailsRoute,
  StudentsIdEditRoute: StudentsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
